services:
  web-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-portfolio-service
    restart: unless-stopped
    networks:
      - quellkasten-project_quellkasten_web

networks:
  quellkasten-project_quellkasten_web:
    external: true
